# robotpy.toml â€” FRC Team 5421 | Swerve Drive Only
# Run: python -m robotpy sync
# Run: python -m robotpy deploy

[tool.robotpy]
robotpy_version = "2026.0.0"

requires = [
    "robotpy[all]",
    "robotpy-rev",        # SparkMAX / SparkFlex
    "robotpy-phoenix6",   # CANcoder
    "robotpy-navx",       # NavX IMU
]
